// Language Context for bilingual support (EN/AR)
import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.newHeliopolis': 'New Heliopolis',
    'nav.beitElWatan': 'Beit El-Watan',
    'nav.about': 'About Us',
    'nav.contact': 'Contact us',
    
    // Hero Section
    'hero.title1': 'Find Your',
    'hero.title2': 'Perfect',
    'hero.title3': 'Investment',
    'hero.subtitle': "Premium properties in Egypt's most sought-after locations",
    
    // Filter Card
    'filter.location': 'Location',
    'filter.location.all': 'All Locations',
    'filter.location.newCairo': 'New Cairo',
    'filter.location.cairo': 'Cairo',
    'filter.location.newHeliopolis': 'New Heliopolis',
    'filter.location.beitAlWatan': 'Beit Al-Watan',
    'filter.bedrooms': 'Bedrooms',
    'filter.bathrooms': 'Bathrooms',
    'filter.floor': 'Floor',
    'filter.any': 'Any',
    'filter.searchButton': 'Search Properties',
    
    // Projects Section
    'projects.title': 'Our Featured Projects',
    'projects.subtitle': 'Discover exceptional living spaces in prime locations',
    'projects.newHeliopolis.title': 'New Heliopolis',
    'projects.newHeliopolis.description': 'A modern residential compound featuring luxury apartments and penthouses in the heart of New Cairo with world-class amenities.',
    'projects.beitElWatan.title': 'Beit El-Watan',
    'projects.beitElWatan.description': 'Premium residential community offering spacious villas and townhouses with contemporary architecture and comprehensive facilities.',
    'projects.exploreButton': 'Explore Project',
    
    // Buildings Map
    'map.title': 'Explore Our Locations',
    'map.subtitle': 'Click on any pin to view building details',
    'map.description': 'Discover our premium real estate developments across Cairo. Click on any pin to view building details.',
    'map.loading': 'Loading map...',
    'map.viewDetails': 'View Details',
    'map.units': 'units',
    'map.startingFrom': 'Starting from',
    
    // Achievements Section
    'achievements.title': 'Our Achievements',
    'achievements.subtitle': 'Building trust through excellence and delivering exceptional results for over a decade',
    'achievements.buildings': 'Completed Buildings',
    'achievements.clients': 'Happy Clients',
    'achievements.awards': 'Industry Awards',
    'achievements.years': 'Years of Excellence',
    'achievements.imageTitle1': 'Premium Developments',
    'achievements.imageTitle2': 'Satisfied Homeowners',
    'achievements.cta': 'Join thousands of satisfied clients who chose Al-Fouad for their dream homes',
    'achievements.ctaButton': 'Start Your Journey',
    
    // Footer
    'footer.about.title': 'About Al-Fouad',
    'footer.about.text': 'Leading real estate investment company in Egypt, delivering premium properties and exceptional living experiences since 2005.',
    'footer.description': 'Your trusted partner in premium real estate investment across Egypt. Building dreams, creating value.',
    'footer.quickLinks': 'Quick Links',
    'footer.cities': 'Cities',
    'footer.contact.title': 'Contact Us',
    'footer.contact.location': 'Cairo, Egypt',
    'footer.contact.address': '123 Business District, New Cairo, Egypt',
    'footer.contact.phone': '+20 123 456 7890',
    'footer.contact.email': 'info@alfouad.com',
    'footer.timeline': 'Construction Timeline',
    'footer.copyright': '© 2026 Al-Fouad Real Estate Investment. All rights reserved.',
    
    // City Details
    'cityDetails.breadcrumb.home': 'Home',
    'cityDetails.overview': 'City Overview',
    'cityDetails.availableBuildings': 'Available Buildings',
    'cityDetails.building': 'Building',
    'cityDetails.units': 'Units',
    'cityDetails.viewUnits': 'View Units',
    'cityDetails.selectBuilding': 'Select a building to view available units',
    'cityDetails.noUnits': 'No units available',
    'cityDetails.availableUnits': 'Available Units in Building',
    'cityDetails.featuredUnits': 'Featured Premium Units',
    'cityDetails.allUnits': 'View All Units',
    'cityDetails.notFound': 'City not found',
    'cityDetails.totalBuildings': 'Total Buildings',
    'cityDetails.totalUnits': 'Total Units',
    'cityDetails.cityStatus': 'City Status',
    'cityDetails.readyToMove': 'Ready to Move',
    'cityDetails.priceRange': 'Price Range',
    'cityDetails.competitive': 'Competitive',
    'cityDetails.location': 'City Location',
    'cityDetails.ourBuildings': 'Our Buildings',
    'cityDetails.noBuildingsAvailable': 'No buildings available at the moment',
    'cityDetails.soldOut': 'Sold Out',
    'cityDetails.available': 'Available',
    'cityDetails.floors': 'Floors',
    'cityDetails.noLocationData': 'Location data not available',
    'cityDetails.coordinates': 'Coordinates',
    
    // Unit Card
    'unit.area': 'Area',
    'unit.bedrooms': 'Bedrooms',
    'unit.bathrooms': 'Bathrooms',
    'unit.floor': 'Floor',
    'unit.viewDetails': 'View Details',
    'unit.price': 'Price',
    'unit.installment': 'Installment',
    'unit.cash': 'Cash',
    'unit.years': 'years',
    
    // Unit Details
    'unitDetails.breadcrumb.home': 'Home',
    'unitDetails.unitType': 'Unit Type',
    'unitDetails.priceDetails': 'Price Details',
    'unitDetails.cashPrice': 'Cash Price',
    'unitDetails.installmentPlan': 'Installment Plan',
    'unitDetails.downPayment': 'Down Payment',
    'unitDetails.monthlyPayment': 'Monthly Payment',
    'unitDetails.duration': 'Duration',
    'unitDetails.years': 'years',
    'unitDetails.features': 'Features & Amenities',
    'unitDetails.overview': 'Unit Overview',
    'unitDetails.specifications': 'Specifications',
    'unitDetails.location': 'Location',
    'unitDetails.contactAgent': 'Contact Agent',
    'unitDetails.scheduleViewing': 'Schedule Viewing',
    
    // Search Results
    'search.results': 'Search Results',
    'search.noResults': 'No properties found',
    'search.noResultsText': 'Try adjusting your search filters to find more properties',
    'search.backToHome': 'Back to Home',
    'search.properties': 'Properties',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.egp': 'EGP',
    'common.million': 'M',
    
    // Testimonials
    'testimonials.title': 'What Our Clients Say',
    'testimonials.subtitle': 'Hear from satisfied homeowners who trusted us with their investment',
    'testimonials.client1.name': 'Ahmed Hassan',
    'testimonials.client1.role': 'Property Owner',
    'testimonials.client1.content': 'Al-Fouad exceeded my expectations. The quality of construction and attention to detail in New Heliopolis is outstanding. Highly recommended!',
    'testimonials.client2.name': 'Sarah Mohamed',
    'testimonials.client2.role': 'Investor',
    'testimonials.client2.content': 'Professional team and transparent process. They guided me through every step of purchasing my villa in Beit El-Watan. Couldn\'t be happier!',
    'testimonials.client3.name': 'Khaled Ibrahim',
    'testimonials.client3.role': 'Homeowner',
    'testimonials.client3.content': 'The best real estate investment I\'ve made. Premium location, excellent amenities, and a company that truly cares about its clients.',
    
    // Testimonials Highlight
    'testimonialsHighlight.stat': '95%',
    'testimonialsHighlight.statLabel': 'Client satisfaction rate',
    'testimonialsHighlight.quote': 'Al-Fouad has allowed us to acquire our customers into the vertical nationally, and to expand into new markets, which has been a massive growth year-over-year.',
    'testimonialsHighlight.author': 'Omar Mansour',
    'testimonialsHighlight.authorRole': 'Real Estate Investor & Developer',
    
    // Hero Section Cards
    'hero.premiumLocations': 'Premium Locations',
    'hero.highROI': 'High ROI',
    'hero.trustedDeveloper': 'Trusted Developer',
    'hero.exploreProperties': 'Explore Properties',
    'hero.rating': 'Rating',
    'hero.fromClients': 'from 500+ clients',
    'hero.featured': 'Featured',
    'hero.luxuryApartments': 'Luxury apartments in premium location',
    'hero.startingFrom': 'Starting from',
    'hero.investmentGrowth': 'Investment Growth',
    'hero.aboveMarket': 'Above market average',
    'hero.seniorAgent': 'Senior Agent',
    'hero.clients': 'clients',
    
    // About Us Page
    'about.hero.title': 'About Al-Fouad',
    'about.hero.subtitle': 'Building Dreams, Creating Communities, Shaping the Future of Real Estate in Egypt',
    'about.story.title': 'Our Story',
    'about.story.p1': 'Founded with a vision to transform the real estate landscape in Egypt, Al-Fouad Real Estate Investment has been at the forefront of premium property development for over a decade. Our journey began with a simple yet powerful commitment: to create exceptional living spaces that combine luxury, functionality, and sustainability.',
    'about.story.p2': 'Today, we stand as one of Egypt\'s most trusted real estate developers, with a portfolio of prestigious projects across New Cairo and beyond. Our success is built on three pillars: unwavering quality, customer satisfaction, and innovative design.',
    'about.story.p3': 'Every project we undertake reflects our dedication to excellence and our belief that home is more than just a building—it\'s where life\'s most precious moments unfold.',
    'about.yearsExcellence': 'Years of Excellence',
    'about.mission.title': 'Our Mission',
    'about.mission.text': 'To deliver world-class real estate solutions that exceed expectations, enrich communities, and provide exceptional value to our clients. We are committed to building sustainable developments that stand the test of time and contribute positively to Egypt\'s urban landscape.',
    'about.vision.title': 'Our Vision',
    'about.vision.text': 'To be recognized as Egypt\'s leading real estate developer, known for innovation, integrity, and creating vibrant communities where people thrive. We envision a future where every Al-Fouad project becomes a landmark of excellence and a symbol of quality living.',
    'about.coreValues.title': 'Our Core Values',
    'about.coreValues.subtitle': 'These principles guide every decision we make and every project we deliver',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.text': 'We pursue the highest standards in everything we do, from design to delivery.',
    'about.values.integrity.title': 'Integrity',
    'about.values.integrity.text': 'Transparency and honesty form the foundation of all our relationships.',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.text': 'We embrace cutting-edge solutions to create smarter, better living spaces.',
    'about.values.sustainability.title': 'Sustainability',
    'about.values.sustainability.text': 'Building responsibly for today while protecting tomorrow\'s environment.',
    'about.achievements.title': 'Our Achievements',
    'about.achievements.projects': 'Completed Projects',
    'about.achievements.families': 'Happy Families',
    'about.achievements.locations': 'Prime Locations',
    'about.achievements.awards': 'Industry Awards',
    'about.whyChoose.title': 'Why Choose Al-Fouad?',
    'about.whyChoose.subtitle': 'We go beyond building properties—we create legacies',
    'about.whyChoose.1.title': 'Prime Locations',
    'about.whyChoose.1.text': 'Strategically positioned in Cairo\'s most sought-after areas, offering convenience, accessibility, and future appreciation.',
    'about.whyChoose.2.title': 'Premium Quality',
    'about.whyChoose.2.text': 'Using only the finest materials and partnering with renowned contractors to ensure superior construction quality.',
    'about.whyChoose.3.title': 'Flexible Payment',
    'about.whyChoose.3.text': 'Customized payment plans designed to make your dream home affordable with transparent pricing and no hidden costs.',
    'about.whyChoose.4.title': 'Modern Design',
    'about.whyChoose.4.text': 'Contemporary architecture that blends aesthetics with functionality, creating spaces that inspire and delight.',
    'about.whyChoose.5.title': 'After-Sales Service',
    'about.whyChoose.5.text': 'Dedicated support team available even after handover, ensuring your peace of mind and complete satisfaction.',
    'about.whyChoose.6.title': 'Timely Delivery',
    'about.whyChoose.6.text': 'Proven track record of completing projects on schedule, respecting your time and investment.',
    'about.cta.title': 'Ready to Find Your Dream Home?',
    'about.cta.subtitle': 'Join thousands of satisfied homeowners who trusted Al-Fouad to deliver their perfect living space',
    'about.cta.explore': 'Explore Our Projects',
    'about.cta.contact': 'Contact Us',
    
    // Building Details Page
    'building.loading': 'Loading building details...',
    'building.notFound': 'Building not found',
    'building.backToHome': 'Back to Home',
    'building.home': 'Home',
    'building.area': 'Area',
    'building.bedrooms': 'Bedrooms',
    'building.bathrooms': 'Bathrooms',
    'building.price': 'Price',
    'building.installment': 'Installment',
    'building.viewDetails': 'View Details',
    'building.gallery': 'Building Gallery',
    'building.aboutBuilding': 'About Building',
    'building.descriptionExtra': 'Featuring state-of-the-art facilities, spacious layouts, and premium finishes throughout. Each unit is carefully designed to maximize comfort and functionality while maintaining the highest standards of quality.',
    'building.quickStats': 'Quick Stats',
    'building.totalFloors': 'Total Floors',
    'building.totalUnits': 'Total Units',
    'building.buildingArea': 'Building Area',
    'building.status': 'Status',
    'building.underConstruction': 'Under Construction',
    'building.deliveryDate': 'Delivery Date',
    'building.expectedDelivery': 'Expected delivery',
    'building.constructionProgress': 'Construction Progress',
    'building.timeRemaining': 'Time Remaining',
    'building.months': 'months',
    'building.untilCompletion': 'Until completion',
    'building.constructionTimeline': 'Construction Timeline',
    'building.timeline.planning': 'Planning & Design',
    'building.timeline.planningDesc': 'Architectural design and planning approval completed',
    'building.timeline.foundation': 'Foundation Work',
    'building.timeline.foundationDesc': 'Foundation and basement construction completed',
    'building.timeline.structure': 'Structural Construction',
    'building.timeline.structureDesc': 'Main structure and framework completed',
    'building.timeline.finishing': 'Finishing Works',
    'building.timeline.finishingDesc': 'Interior and exterior finishing in progress',
    'building.timeline.delivery': 'Handover & Delivery',
    'building.timeline.deliveryDesc': 'Final inspections and unit handover',
    'building.completed': 'Completed',
    'building.inProgress': 'In Progress',
    'building.upcoming': 'Upcoming',
    'building.locationMap': 'Location Map',
    'building.nearbyLandmark1': '5 mins to Cairo Festival City',
    'building.nearbyLandmark2': '10 mins to AUC',
    'building.nearbyLandmark3': '15 mins to New Capital',
    'building.availableUnits': 'Available Units',
    'building.noUnitsAvailable': 'No units available in this building',
    'building.noTimelineAvailable': 'No construction timeline available for this building',
    'building.floor': 'Floor',
    'building.years': 'years',
    
    // Contact Sales Section
    'contact.title': 'Contact Our',
    'contact.titleHighlight': 'Sales Team',
    'contact.subtitle': 'Ready to make your dream investment? Our expert team is here to guide you every step of the way.',
    'contact.getInTouch': 'Get In Touch',
    'contact.description': 'Have questions or ready to schedule a visit? We\'re here to help you find the perfect property that matches your needs and investment goals.',
    'contact.address': 'Office Address',
    'contact.addressValue': 'New Cairo, Cairo Governorate, Egypt',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.workingHours': 'Working Hours',
    'contact.weekdays': 'Sunday - Thursday',
    'contact.saturday': 'Saturday',
    'contact.friday': 'Friday',
    'contact.closed': 'Closed',
    'contact.sendMessage': 'Send Us a Message',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'e.g., Property Inquiry',
    'contact.form.sending': 'Sending...',
    'contact.successMessage': 'Thank you! Your message has been sent successfully. We\'ll get back to you shortly.',
    'contact.findUs': 'Find Us on the Map',
    'contact.mapTitle': 'Al-Fouad Real Estate Location',
    'contact.backToHome': 'Back to Home',
    'contact.availability': 'We\'re available 24/7 to answer your questions and help you find the perfect property.',
    'contact.callUs': 'Call Us',
    'contact.emailUs': 'Email Us',
    'contact.visitUs': 'Visit Us',
    'contact.businessHours': 'Business Hours',
    'contact.hours.weekdays': 'Monday - Friday:',
    'contact.hours.weekdaysTime': '9:00 AM - 8:00 PM',
    'contact.hours.saturday': 'Saturday:',
    'contact.hours.saturdayTime': '10:00 AM - 6:00 PM',
    'contact.hours.sunday': 'Sunday:',
    'contact.hours.sundayTime': 'Closed',
    'contact.form.title': 'Send Us a Message',
    'contact.form.name': 'Full Name *',
    'contact.form.namePlaceholder': 'John Doe',
    'contact.form.email': 'Email Address *',
    'contact.form.emailPlaceholder': 'john@example.com',
    'contact.form.phone': 'Phone Number *',
    'contact.form.phonePlaceholder': '+20 123 456 7890',
    'contact.form.message': 'Your Message *',
    'contact.form.messagePlaceholder': 'Tell us about your requirements...',
    'contact.form.city': 'Interested City',
    'contact.form.cityPlaceholder': 'Select a city (optional)',
    'contact.form.submit': 'Send Message',
    'contact.tour.title': 'Schedule a Site Visit',
    'contact.tour.subtitle': 'Experience our premium properties firsthand with a personalized tour',
    'contact.tour.button': 'Book a Tour',
  },
  ar: {
    // Navbar
    'nav.home': 'الرئيسية',
    'nav.newHeliopolis': 'هليوبوليس الجديدة',
    'nav.beitElWatan': 'بيت الوطن',
    'nav.about': 'معلومات عنا',
    'nav.contact': 'تواصل معنا',
    
    // Hero Section
    'hero.title1': 'اعثر على',
    'hero.title2': 'الاستثمار المثالي',
    'hero.title3': 'لك',
    'hero.subtitle': 'عقارات فاخرة في أكثر المواقع المرموقة في مصر',
    
    // Filter Card
    'filter.location': 'الموقع',
    'filter.location.all': 'جميع المواقع',
    'filter.location.newCairo': 'القاهرة الجديدة',
    'filter.location.cairo': 'القاهرة',
    'filter.location.newHeliopolis': 'هليوبوليس الجديدة',
    'filter.location.beitAlWatan': 'بيت الوطن',
    'filter.bedrooms': 'غرف النوم',
    'filter.bathrooms': 'الحمامات',
    'filter.floor': 'الطابق',
    'filter.any': 'أي',
    'filter.searchButton': 'بحث عن عقارات',
    
    // Projects Section
    'projects.title': 'مشاريعنا المميزة',
    'projects.subtitle': 'اكتشف مساحات معيشية استثنائية في مواقع متميزة',
    'projects.newHeliopolis.title': 'هليوبوليس الجديدة',
    'projects.newHeliopolis.description': 'مجمع سكني حديث يضم شققاً فاخرة وبنتهاوس في قلب القاهرة الجديدة مع مرافق عالمية المستوى.',
    'projects.beitElWatan.title': 'بيت الوطن',
    'projects.beitElWatan.description': 'مجتمع سكني فاخر يقدم فيلات وتاون هاوس واسعة بتصميم معماري عصري ومرافق شاملة.',
    'projects.exploreButton': 'استكشف المشروع',
    
    // Buildings Map
    'map.title': 'استكشف مواقعنا',
    'map.subtitle': 'انقر على أي دبوس لعرض تفاصيل المبنى',
    'map.description': 'اكتشف تطويرات العقارات الفاخرة لدينا عبر القاهرة. انقر على أي دبوس لعرض تفاصيل المبنى.',
    'map.loading': 'جاري تحميل الخريطة...',
    'map.viewDetails': 'عرض التفاصيل',
    'map.units': 'وحدة',
    'map.startingFrom': 'تبدأ من',
    
    // Achievements Section
    'achievements.title': 'إنجازاتنا',
    'achievements.subtitle': 'بناء الثقة من خلال التميز وتقديم نتائج استثنائية لأكثر من عقدة',
    'achievements.buildings': 'المباني المكتملة',
    'achievements.clients': 'عملاء سعداء',
    'achievements.awards': 'جوائز صناعية',
    'achievements.years': 'سنوات التميز',
    'achievements.imageTitle1': 'مشاريع فاخرة',
    'achievements.imageTitle2': 'مستثمري العقارات سعداء',
    'achievements.cta': 'انضم إلى الآلاف من العملاء السعداء الذين اختاروا الفؤاد لمنازلهم المثالية',
    'achievements.ctaButton': 'ابدأ رحلتك',
    
    // Footer
    'footer.about.title': 'عن الفؤاد',
    'footer.about.text': 'شركة رائدة في الاستثمار العقاري في مصر، تقدم عقارات فاخرة وتجارب معيشية استثنائية منذ عام 2005.',
    'footer.description': 'شريكك الموثوق في استثمارات العقارات الفاخرة عبر مصر. بناء الأحلام، إنشاء قيمة.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.cities': 'المدن',
    'footer.contact.title': 'تواصل معنا',
    'footer.contact.location': 'القاهرة، مصر',
    'footer.contact.address': '123 الحي التجاري، القاهرة الجديدة، مصر',
    'footer.contact.phone': '+20 123 456 7890',
    'footer.contact.email': 'info@alfouad.com',
    'footer.timeline': 'جدول البناء',
    'footer.copyright': '© 2026 الفؤاد للاستثمار العقاري. جميع الحقوق محفوظة.',
    
    // City Details
    'cityDetails.breadcrumb.home': 'الرئيسية',
    'cityDetails.overview': 'نظرة عامة على المدينة',
    'cityDetails.availableBuildings': 'المباني المتاحة',
    'cityDetails.building': 'مبنى',
    'cityDetails.units': 'وحدة',
    'cityDetails.viewUnits': 'عرض الوحدات',
    'cityDetails.selectBuilding': 'اختر مبنى لعرض الوحدات المتاحة',
    'cityDetails.noUnits': 'لا توجد وحدات متاحة',
    'cityDetails.availableUnits': 'الوحدات المتاحة في المبنى',
    'cityDetails.featuredUnits': 'الوحدات الفاخرة المميزة',
    'cityDetails.allUnits': 'عرض جميع الوحدات',
    'cityDetails.notFound': 'المدينة غير موجودة',
    'cityDetails.totalBuildings': 'إجمالي المباني',
    'cityDetails.totalUnits': 'إجمالي الوحدات',
    'cityDetails.cityStatus': 'حالة المدينة',
    'cityDetails.readyToMove': 'جاهز للانتقال',
    'cityDetails.priceRange': 'نطاق السعر',
    'cityDetails.competitive': 'منافس',
    'cityDetails.location': 'موقع المدينة',
    'cityDetails.ourBuildings': 'مبانينا',
    'cityDetails.noBuildingsAvailable': 'لا توجد مباني متاحة حالياً',
    'cityDetails.soldOut': 'مكتمل البيع',
    'cityDetails.available': 'متاح',
    'cityDetails.floors': 'الطوابق',
    'cityDetails.noLocationData': 'لا توجد بيانات الموقع',
    'cityDetails.coordinates': 'الإحداثيات',
    
    // Unit Card
    'unit.area': 'المساحة',
    'unit.bedrooms': 'غرف النوم',
    'unit.bathrooms': 'الحمامات',
    'unit.floor': 'الطابق',
    'unit.viewDetails': 'عرض التفاصيل',
    'unit.price': 'السعر',
    'unit.installment': 'تقسيط',
    'unit.cash': 'كاش',
    'unit.years': 'سنوات',
    
    // Unit Details
    'unitDetails.breadcrumb.home': 'الرئيسية',
    'unitDetails.unitType': 'نوع الوحدة',
    'unitDetails.priceDetails': 'تفاصيل السعر',
    'unitDetails.cashPrice': 'السعر كاش',
    'unitDetails.installmentPlan': 'خطة التقسيط',
    'unitDetails.downPayment': 'المقدم',
    'unitDetails.monthlyPayment': 'القسط الشهري',
    'unitDetails.duration': 'المدة',
    'unitDetails.years': 'سوات',
    'unitDetails.features': 'المميزات والمرافق',
    'unitDetails.overview': 'نظرة عامة على الوحدة',
    'unitDetails.specifications': 'المواصفات',
    'unitDetails.location': 'الموقع',
    'unitDetails.contactAgent': 'تواصل مع الوكيل',
    'unitDetails.scheduleViewing': 'حجز موعد للمعاينة',
    
    // Search Results
    'search.results': 'نتائج البحث',
    'search.noResults': 'لم يتم العثور على عقارات',
    'search.noResultsText': 'حاول تعديل فلاتر البحث للعثور على المزيد من العقارات',
    'search.backToHome': 'العودة للرئيسية',
    'search.properties': 'عقار',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.egp': 'جنيه',
    'common.million': 'مليون',
    
    // Testimonials
    'testimonials.title': 'آراء عملائنا',
    'testimonials.subtitle': 'استمع إلى أصحاب المنازل الراضين الذين وثقوا بنا في استثماراتهم',
    'testimonials.client1.name': 'أحمد حسن',
    'testimonials.client1.role': 'مالك عقار',
    'testimonials.client1.content': 'الفؤاد تجاوزت توقعاتي. جودة البناء والاهتمام بالتفاصيل في هليوبوليس الجديدة رائعة. أنصح بشدة!',
    'testimonials.client2.name': 'سارة محمد',
    'testimonials.client2.role': 'مستثمري',
    'testimonials.client2.content': 'فريق محترف وعملية شفافة. قاموا بإرشادي في كل خطوة لشراء الفيلا الخاصة بي في بيت الوطن. لا يمكن أن أكون أكثر سعادة!',
    'testimonials.client3.name': 'خالد إبراهيم',
    'testimonials.client3.role': 'مالك منزل',
    'testimonials.client3.content': 'أفضل استثمار عقاري قمت به. موقع مميز، ومرافق ممتازة، وشركة تهتم حقاً بعملائها.',
    
    // Testimonials Highlight
    'testimonialsHighlight.stat': '95%',
    'testimonialsHighlight.statLabel': 'نسبة رضا العملاء',
    'testimonialsHighlight.quote': 'الفؤاد سمح لنا بتقديم عملائنا في القطاع الوطني، وتوسيعنا في أسواق جديدة، مما كان نمواً هائلاً من سنة لأخرى.',
    'testimonialsHighlight.author': 'أحمد منصور',
    'testimonialsHighlight.authorRole': 'مستثمر ومستثمري عقاري',
    
    // Hero Section Cards
    'hero.premiumLocations': 'مواقع مميزة',
    'hero.highROI': 'عائد استثماري عالي',
    'hero.trustedDeveloper': 'مطور موثوق',
    'hero.exploreProperties': 'استكشف العقارات',
    'hero.rating': 'التقييم',
    'hero.fromClients': 'من 500+ عميل',
    'hero.featured': 'مميز',
    'hero.luxuryApartments': 'شقق فاخرة في موقع مميز',
    'hero.startingFrom': 'يبدأ من',
    'hero.investmentGrowth': 'نمو الاستثمار',
    'hero.aboveMarket': 'أعلى من متوسط السوق',
    'hero.seniorAgent': 'وكيل أول',
    'hero.clients': 'عميل',
    
    // About Us Page
    'about.hero.title': 'عن الفؤاد',
    'about.hero.subtitle': 'بناء الأحلام، إنشاء المجتمعات، تشكيل مستقبل العقارات في مصر',
    'about.story.title': 'قصتنا',
    'about.story.p1': 'تأسست برؤية لتحويل المشهد العقاري في مصر، وكانت الفؤاد للاستثمار العقاري في طليعة تطوير العقار الفاخر لأكثر من عقد من الزمان. بدأت رحلتنا بالتزام بسيط ولكنه قوي: إنشاء مساحات معيشية استثنائية تجمع بين الفخامة والوظائف والاستدامة.',
    'about.story.p2': 'اليوم، نقف كواحد من أكثر مطوري العقارات الموثوق بهم في مصر، مع محفظة من المشاريع المرموقة في القاهرة الجديدة وخارجها. يُبنى نجاحنا على ثلاثة أعمدة: الجودة الثابتة، ورضا العملاء، والتصميم المبتكر.',
    'about.story.p3': 'كل مشروع نقوم به يعكس تفانينا في التميز واعتقادنا بأن المنزل هو أكثر من مجرد مبنى - إنه المكان الذي تتكشف فيه أثمن لحظات الحياة.',
    'about.yearsExcellence': 'سنوات من التميز',
    'about.mission.title': 'مهمتنا',
    'about.mission.text': 'تقديم حلول عقارية عالمية المستوى تتجاوز التوقعات، وتثري المجتمعات، وتوفر قيمة استثنائية لعملائنا. نحن ملتزمون ببناء تطورات مستدامة تصمد أمام اختبار الزمن وتساهم بشكل إيجابي في المشهد الضري في مصر.',
    'about.vision.title': 'رؤيتنا',
    'about.vision.text': 'أن نكون معترف بنا كمطور عقاري رائد في مصر، معروف بالابتكار والنزاهة وإنشاء مجتمعات نابضة بالحياة حيث يزدهر الناس. نتصور مستقبلاً حيث يصبح كل مشروع للفؤاد معلماً للتميز ورمزاً للحياة الراقية.',
    'about.coreValues.title': 'قيمنا الأساسية',
    'about.coreValues.subtitle': 'هذه المبادئ توجه كل قرار نتخذه وكل مشروع نقدمه',
    'about.values.excellence.title': 'التميز',
    'about.values.excellence.text': 'نسعى لأعلى المعايير في كل ما نفعله، من التصميم إلى التسليم.',
    'about.values.integrity.title': 'النزاهة',
    'about.values.integrity.text': 'الشفافية والصدق يشكلان أساس جميع علاقاتنا.',
    'about.values.innovation.title': 'الابتكار',
    'about.values.innovation.text': 'نتبنى حلولاً متطورة لإنشاء مساحات معيشية أكثر ذكاءً وأفضل.',
    'about.values.sustainability.title': 'الاستدامة',
    'about.values.sustainability.text': 'البناء بمسؤولية لليوم مع حماية بيئة الغد.',
    'about.achievements.title': 'إنجازاتنا',
    'about.achievements.projects': 'مشاريع مكتملة',
    'about.achievements.families': 'عائلات سعيدة',
    'about.achievements.locations': 'مواقع متميزة',
    'about.achievements.awards': 'جوائز صناعية',
    'about.whyChoose.title': 'لماذا تختار الفؤاد؟',
    'about.whyChoose.subtitle': 'نحن نتجاوز بناء العقارات - نحن ننشئ إرثاً',
    'about.whyChoose.1.title': 'مواقع متميزة',
    'about.whyChoose.1.text': 'تم وضعها بشكل استراتيجي في المناطق الأكثر طلباً في القاهرة، مما يوفر الراحة وسهولة الوصول والتقدير المستقبلي.',
    'about.whyChoose.2.title': 'جودة فاخرة',
    'about.whyChoose.2.text': 'استخدام فضل المواد فقط والشراكة مع مقاولين مشهورين لضمان جودة البناء الفائقة.',
    'about.whyChoose.3.title': 'دفع مرن',
    'about.whyChoose.3.text': 'خطط دفع مخصصة مصممة لجعل منزل أحلامك ميسور التكلفة مع تسعير شفاف ولا توجد تكاليف خفية.',
    'about.whyChoose.4.title': 'تصميم حديث',
    'about.whyChoose.4.text': 'هندسة معمارية معاصرة تمزج بين الجماليات والوظائف، مما يخلق مساحات تلهم وتبهج.',
    'about.whyChoose.5.title': 'خدمة ما بعد البيع',
    'about.whyChoose.5.text': 'فريق دعم مخصص متاح حتى بعد التسليم، مما يضمن راحة بالك والرضا التام.',
    'about.whyChoose.6.title': 'التسليم في الوقت المناسب',
    'about.whyChoose.6.text': 'سجل حافل مثبت في إكمال المشاريع في الموعد المحدد، مع احترام وقتك واستثمارك.',
    'about.cta.title': 'هل أنت مستعد للعثور على منزل أحلامك؟',
    'about.cta.subtitle': 'انضم إلى الآلاف من مالكي المنازل الراضين الذين وثقوا بالفؤاد لتقديم مساحة معيشتهم المثالية',
    'about.cta.explore': 'استكشف مشاريعنا',
    'about.cta.contact': 'اتصل بنا',
    
    // Building Details Page
    'building.loading': 'جاري تحميل تفصيل المبنى...',
    'building.notFound': 'المبنى غير موجود',
    'building.backToHome': 'العودة للرئيسية',
    'building.home': 'الرئيسية',
    'building.area': 'المساحة',
    'building.bedrooms': 'غرف النوم',
    'building.bathrooms': 'الحمامات',
    'building.price': 'السعر',
    'building.installment': 'التقسيط',
    'building.viewDetails': 'عرض التفاصيل',
    'building.gallery': 'معرض المبنى',
    'building.aboutBuilding': 'عن المبنى',
    'building.descriptionExtra': 'تتميز بمعدات حديثة، تصميمات فضائية وتشطيبات فاخرة على مداره. يتم تصميم كل وحدة بعناية لتعزيز الراحة والوظائف مع الحفاظ على أعلى معايير الجودة.',
    'building.quickStats': 'إحصائيات سريعة',
    'building.totalFloors': 'إجمالي الطوابق',
    'building.totalUnits': 'إجمالي الوحدات',
    'building.buildingArea': 'مساحة المبنى',
    'building.status': 'الحالة',
    'building.underConstruction': 'قيد البناء',
    'building.deliveryDate': 'تاريخ التسليم',
    'building.expectedDelivery': 'التوصيل المتوقع',
    'building.constructionProgress': 'تقدم البناء',
    'building.timeRemaining': 'الوقت المتبقي',
    'building.months': 'أشهر',
    'building.untilCompletion': 'حتى الانتهاء',
    'building.constructionTimeline': 'جدول البناء',
    'building.timeline.planning': 'التخطيط والتصميم',
    'building.timeline.planningDesc': 'تم إكمال تصميم العمارة والموافقة على التخطيط',
    'building.timeline.foundation': 'العملات الأساسية',
    'building.timeline.foundationDesc': 'تم إكمال العملات الأساسية والقبوسة',
    'building.timeline.structure': 'بناء الهيكل',
    'building.timeline.structureDesc': 'تم إكمال الهيكل الرئيسي والهيكل الأساسي',
    'building.timeline.finishing': 'الأعمال النهائية',
    'building.timeline.finishingDesc': 'التشطيبات الداخلية والخارجية في التقدم',
    'building.timeline.delivery': 'تسليم وتسليم الوحدات',
    'building.timeline.deliveryDesc': 'التدقيق النهائي وتسليم الوحدات',
    'building.completed': 'مكتمل',
    'building.inProgress': 'قيد التقدم',
    'building.upcoming': 'قادم',
    'building.locationMap': 'خريطة الموقع',
    'building.nearbyLandmark1': '5 دقائق إلى مدينة القاهرة الفستيفال',
    'building.nearbyLandmark2': '10 دقائق إلى جامعة القاهرة الأمريكية',
    'building.nearbyLandmark3': '15 دقائق إلى العاصمة الجديدة',
    'building.availableUnits': 'الوحدات المتاحة',
    'building.noUnitsAvailable': 'لا توجد وحدات متاحة في هذا المبنى',
    'building.noTimelineAvailable': 'لا توجد جدول بناء متاح لهذا المبنى',
    'building.floor': 'الطابق',
    'building.years': 'سنوات',
    
    // Contact Sales Section
    'contact.title': 'اتصل بـ',
    'contact.titleHighlight': 'فريق المبيعات',
    'contact.subtitle': 'هل أنت مستعد لتحقيق استثمار أحلامك؟ فريقنا الخبير هنا لإرشادك في كل خطوة على الطريق.',
    'contact.getInTouch': 'تواصل معنا',
    'contact.description': 'لديك أسئلة أو مستعد لتحديد موعد زيارة؟ نحن هنا لمساعدتك في العثور على العقار المثالي الذي يتناسب مع احتياجاتك وأهداف استثماراتك.',
    'contact.address': 'عنوان المكتب',
    'contact.addressValue': 'القاهرة الجديدة، محافظة القاهرة، مصر',
    'contact.phone': 'الهاتف',
    'contact.email': 'البريد الإلكتروني',
    'contact.workingHours': 'ساعات العمل',
    'contact.weekdays': 'الأحد - الخميس',
    'contact.saturday': 'السبت',
    'contact.friday': 'الجمعة',
    'contact.closed': 'مغلق',
    'contact.sendMessage': 'أرسل لنا رسالة',
    'contact.form.subject': 'الموضوع',
    'contact.form.subjectPlaceholder': 'مثلاً، استفسار عن العقار',
    'contact.form.sending': 'جاري الإرسال...',
    'contact.successMessage': 'شكراً! تم إرسال رسالتك بنجاح. سنعود إليك قريباً.',
    'contact.findUs': 'ابحث عننا على الخريطة',
    'contact.mapTitle': 'موقع الفؤاد للعقارات',
    'contact.backToHome': 'العودة للرئيسية',
    'contact.availability': 'نحن متاحون على مدار الساعة طوال أيام الأسبوع للإجابة على أسئلتك ومساعدتك في العثور على العقار المثالي.',
    'contact.callUs': 'اتصل بنا',
    'contact.emailUs': 'راسلنا',
    'contact.visitUs': 'قم بزيارتنا',
    'contact.businessHours': 'ساعات العمل',
    'contact.hours.weekdays': 'الاثنين - الجمعة:',
    'contact.hours.weekdaysTime': '9:00 صباحاً - 8:00 مساءً',
    'contact.hours.saturday': 'السبت:',
    'contact.hours.saturdayTime': '10:00 صباحاً - 6:00 مساءً',
    'contact.hours.sunday': 'الأحد:',
    'contact.hours.sundayTime': 'مغلق',
    'contact.form.title': 'أرسل لنا رسالة',
    'contact.form.name': 'الاسم الكامل *',
    'contact.form.namePlaceholder': 'أحمد محمد',
    'contact.form.email': 'البريد الإلكتروني *',
    'contact.form.emailPlaceholder': 'ahmed@example.com',
    'contact.form.phone': 'رقم الهاتف *',
    'contact.form.phonePlaceholder': '+20 123 456 7890',
    'contact.form.message': 'رسالتك *',
    'contact.form.messagePlaceholder': 'أخبرنا عن متطلباتك...',
    'contact.form.city': 'المدينة المفضلة',
    'contact.form.cityPlaceholder': 'اختر مدينة (اختياري)',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.tour.title': 'حدد موعد زيارة الموقع',
    'contact.tour.subtitle': 'اختبر عقاراتنا الفاخرة شخصياً من خلال جولة مخصصة',
    'contact.tour.button': 'احجز جولة',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  const value = {
    language,
    toggleLanguage,
    t,
    dir
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}